package normalize

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/kdse/runtime/internal/types"
)

const kdseVersion = "1.0.0"

// Generator creates KDSE-standard documents from existing documentation
type Generator struct {
	repoPath    string
	sessionID   string
	kdseDir     string
}

// NewGenerator creates a new KDSE document generator
func NewGenerator(repoPath, sessionID string) *Generator {
	return &Generator{
		repoPath:  repoPath,
		sessionID: sessionID,
		kdseDir:   filepath.Join(repoPath, ".kdse", "normalized"),
	}
}

// Generate creates KDSE-standard documents based on the normalization result
func (g *Generator) Generate(result *NormalizationResult) ([]NormalizedArtifact, error) {
	var artifacts []NormalizedArtifact

	// Ensure KDSE normalized directory exists
	if err := os.MkdirAll(g.kdseDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create normalized directory: %w", err)
	}

	// Generate SPEC.md if we have purpose/requirements
	if result.KnowledgeExtract.Purpose != "" || len(result.KnowledgeExtract.Requirements) > 0 {
		artifact, err := g.generateSpec(result)
		if err == nil {
			artifacts = append(artifacts, *artifact)
		}
	}

	// Generate ARCHITECTURE.md if we have architecture docs or decisions
	hasArchitecture := len(g.filterByType(result.DiscoveredDocs, DocsTypeArchitecture, DocsTypeDesign)) > 0
	hasDecisions := len(result.KnowledgeExtract.Decisions) > 0
	if hasArchitecture || hasDecisions {
		artifact, err := g.generateArchitecture(result)
		if err == nil {
			artifacts = append(artifacts, *artifact)
		}
	}

	// Generate GLOSSARY.md if we have glossary terms
	if len(result.KnowledgeExtract.Glossary) > 0 {
		artifact, err := g.generateGlossary(result)
		if err == nil {
			artifacts = append(artifacts, *artifact)
		}
	}

	// Generate DECISIONS.md if we have ADR or decisions
	if len(result.KnowledgeExtract.Decisions) > 0 {
		artifact, err := g.generateDecisions(result)
		if err == nil {
			artifacts = append(artifacts, *artifact)
		}
	}

	// Generate GOVERNANCE.md if we have contributing/license info
	hasGovernance := len(g.filterByType(result.DiscoveredDocs, DocsTypeContributing, DocsTypeLicense, DocsTypeChangelog)) > 0
	if hasGovernance {
		artifact, err := g.generateGovernance(result)
		if err == nil {
			artifacts = append(artifacts, *artifact)
		}
	}

	// Generate API.md if we have API documentation
	if len(g.filterByType(result.DiscoveredDocs, DocsTypeAPI)) > 0 {
		artifact, err := g.generateAPI(result)
		if err == nil {
			artifacts = append(artifacts, *artifact)
		}
	}

	// Generate ARTIFACTS.md (index of all KDSE artifacts)
	artifact, err := g.generateArtifactsIndex(result, artifacts)
	if err == nil {
		artifacts = append(artifacts, *artifact)
	}

	return artifacts, nil
}

func (g *Generator) generateSpec(result *NormalizationResult) (*NormalizedArtifact, error) {
	content := fmt.Sprintf(`# Specification

**Document Version:** %s  
**Type:** Engineering Artifact  
**Phase:** Derived  
**Authority:** %s  

---

## Purpose

%s

---

## Domain

%s

---

## Stakeholders

%s

---

## Requirements

%s

---

## Constraints

%s

---

## Traceability

%s

---

*This specification was generated by KDSE Normalization from existing documentation.*
*Original documentation is preserved in its original location.*
*Generated: %s*
`, 
		kdseVersion,
		g.getAuthority(result),
		g.formatPurpose(result.KnowledgeExtract),
		g.formatDomain(result.KnowledgeExtract),
		g.formatStakeholders(result.KnowledgeExtract),
		g.formatRequirements(result.KnowledgeExtract),
		g.formatConstraints(result.KnowledgeExtract),
		g.formatTraceabilityBlock(result, "SPEC.md"),
		time.Now().Format(time.RFC3339),
	)

	path := filepath.Join(g.kdseDir, "SPEC.md")
	if err := g.writeArtifact(path, content); err != nil {
		return nil, err
	}

	return &NormalizedArtifact{
		ID:       "NORM-SPEC-" + g.sessionID,
		Path:     path,
		DocType:  "Specification",
		Title:    "Project Specification",
		Content:  content,
		Traceability: Traceability{
			DerivedFrom:       g.getDerivedFrom(result, DocsTypeREADME, DocsTypeReference),
			OriginalDocuments: g.getOriginalDocPaths(result),
			Authority:         g.getAuthority(result),
			Version:           kdseVersion,
			NormativeRefs:     []string{"docs/foundation/005-engineering-artifacts.md"},
			TransformationType: "Normalization",
		},
		Metadata: ArtifactMetadata{
			Version:     kdseVersion,
			KDSEVersion: kdseVersion,
			Phase:       string(types.PhaseDefined),
			Tags:        []string{"normalized", "specification"},
		},
		CreatedAt: time.Now().Format(time.RFC3339),
	}, nil
}

func (g *Generator) generateArchitecture(result *NormalizationResult) (*NormalizedArtifact, error) {
	content := fmt.Sprintf(`# Architecture

**Document Version:** %s  
**Type:** Engineering Artifact  
**Phase:** Derived  
**Authority:** %s  

---

## Overview

%s

---

## Design Decisions

%s

---

## Components

%s

---

%s

---

*This architecture document was generated by KDSE Normalization from existing documentation.*
*Original documentation is preserved in its original location.*
*Generated: %s*
`,
		kdseVersion,
		g.getAuthority(result),
		g.formatOverview(result),
		g.formatDecisions(result.KnowledgeExtract),
		g.formatComponents(result),
		g.formatTraceabilityBlock(result, "ARCHITECTURE.md"),
		time.Now().Format(time.RFC3339),
	)

	path := filepath.Join(g.kdseDir, "ARCHITECTURE.md")
	if err := g.writeArtifact(path, content); err != nil {
		return nil, err
	}

	return &NormalizedArtifact{
		ID:       "NORM-ARCH-" + g.sessionID,
		Path:     path,
		DocType:  "Architecture",
		Title:    "System Architecture",
		Content:  content,
		Traceability: Traceability{
			DerivedFrom:       g.getDerivedFrom(result, DocsTypeArchitecture, DocsTypeDesign, DocsTypeADR),
			OriginalDocuments: g.getOriginalDocPaths(result),
			Authority:         g.getAuthority(result),
			Version:           kdseVersion,
			NormativeRefs:     []string{"docs/foundation/004-engineering-model.md"},
			TransformationType: "Normalization",
		},
		Metadata: ArtifactMetadata{
			Version:     kdseVersion,
			KDSEVersion: kdseVersion,
			Phase:       string(types.PhaseStructured),
			Tags:        []string{"normalized", "architecture"},
		},
		CreatedAt: time.Now().Format(time.RFC3339),
	}, nil
}

func (g *Generator) generateGlossary(result *NormalizationResult) (*NormalizedArtifact, error) {
	var buf strings.Builder
	buf.WriteString("# Glossary\n\n")
	buf.WriteString("**Document Version:** " + kdseVersion + "\n")
	buf.WriteString("**Type:** Engineering Artifact\n")
	buf.WriteString("**Phase:** Derived\n\n")
	buf.WriteString("---\n\n")
	buf.WriteString("## Terms\n\n")

	for i, term := range result.KnowledgeExtract.Glossary {
		buf.WriteString(fmt.Sprintf("### %s\n\n", term.Term))
		buf.WriteString(fmt.Sprintf("%s\n\n", term.Definition))
		buf.WriteString(fmt.Sprintf("*Source: %s*\n\n", term.Source))
		if i < len(result.KnowledgeExtract.Glossary)-1 {
			buf.WriteString("---\n\n")
		}
	}

	buf.WriteString("---\n\n")
	buf.WriteString(g.formatTraceabilityBlock(result, "GLOSSARY.md"))
	buf.WriteString("\n\n*This glossary was generated by KDSE Normalization from existing documentation.*\n")
	buf.WriteString("*Original documentation is preserved in its original location.*\n")
	buf.WriteString(fmt.Sprintf("*Generated: %s*\n", time.Now().Format(time.RFC3339)))

	content := buf.String()
	path := filepath.Join(g.kdseDir, "GLOSSARY.md")
	if err := g.writeArtifact(path, content); err != nil {
		return nil, err
	}

	return &NormalizedArtifact{
		ID:       "NORM-GLOSS-" + g.sessionID,
		Path:     path,
		DocType:  "Glossary",
		Title:    "Project Glossary",
		Content:  content,
		Traceability: Traceability{
			DerivedFrom:       g.getDerivedFromFromGlossary(result.KnowledgeExtract.Glossary),
			OriginalDocuments: g.getOriginalDocPaths(result),
			Authority:         g.getAuthority(result),
			Version:           kdseVersion,
			NormativeRefs:     []string{"docs/foundation/007-glossary.md"},
			TransformationType: "Normalization",
		},
		Metadata: ArtifactMetadata{
			Version:     kdseVersion,
			KDSEVersion: kdseVersion,
			Phase:       string(types.PhaseDefined),
			Tags:        []string{"normalized", "glossary"},
		},
		CreatedAt: time.Now().Format(time.RFC3339),
	}, nil
}

func (g *Generator) generateDecisions(result *NormalizationResult) (*NormalizedArtifact, error) {
	var buf strings.Builder
	buf.WriteString("# Architecture Decisions\n\n")
	buf.WriteString("**Document Version:** " + kdseVersion + "\n")
	buf.WriteString("**Type:** Engineering Artifact\n")
	buf.WriteString("**Phase:** Derived\n\n")
	buf.WriteString("---\n\n")
	buf.WriteString("## Decisions\n\n")

	for i, decision := range result.KnowledgeExtract.Decisions {
		buf.WriteString(fmt.Sprintf("### %s: %s\n\n", decision.ID, decision.Title))
		buf.WriteString(fmt.Sprintf("**Status:** %s\n\n", decision.Status))
		buf.WriteString("**Context:**\n\n")
		buf.WriteString(decision.Context + "\n\n")
		buf.WriteString("**Decision:**\n\n")
		buf.WriteString(decision.Decision + "\n\n")
		buf.WriteString("**Rationale:**\n\n")
		buf.WriteString(decision.Rationale + "\n\n")
		buf.WriteString(fmt.Sprintf("*Source: %s*\n\n", decision.Source))
		if i < len(result.KnowledgeExtract.Decisions)-1 {
			buf.WriteString("---\n\n")
		}
	}

	buf.WriteString("---\n\n")
	buf.WriteString(g.formatTraceabilityBlock(result, "DECISIONS.md"))
	buf.WriteString("\n\n*This decisions document was generated by KDSE Normalization from existing documentation.*\n")
	buf.WriteString("*Original documentation is preserved in its original location.*\n")
	buf.WriteString(fmt.Sprintf("*Generated: %s*\n", time.Now().Format(time.RFC3339)))

	content := buf.String()
	path := filepath.Join(g.kdseDir, "DECISIONS.md")
	if err := g.writeArtifact(path, content); err != nil {
		return nil, err
	}

	return &NormalizedArtifact{
		ID:       "NORM-DEC-" + g.sessionID,
		Path:     path,
		DocType:  "Decisions",
		Title:    "Architecture Decisions",
		Content:  content,
		Traceability: Traceability{
			DerivedFrom:       g.getDerivedFrom(result, DocsTypeADR, DocsTypeEngineering),
			OriginalDocuments: g.getOriginalDocPaths(result),
			Authority:         g.getAuthority(result),
			Version:           kdseVersion,
			NormativeRefs:     []string{"docs/evolution/ADRS.md"},
			TransformationType: "Normalization",
		},
		Metadata: ArtifactMetadata{
			Version:     kdseVersion,
			KDSEVersion: kdseVersion,
			Phase:       string(types.PhaseStructured),
			Tags:        []string{"normalized", "decisions", "adr"},
		},
		CreatedAt: time.Now().Format(time.RFC3339),
	}, nil
}

func (g *Generator) generateGovernance(result *NormalizationResult) (*NormalizedArtifact, error) {
	var buf strings.Builder
	buf.WriteString("# Governance\n\n")
	buf.WriteString("**Document Version:** " + kdseVersion + "\n")
	buf.WriteString("**Type:** Engineering Artifact\n")
	buf.WriteString("**Phase:** Derived\n\n")
	buf.WriteString("---\n\n")

	// Contributing
	contribDocs := g.filterByType(result.DiscoveredDocs, DocsTypeContributing)
	if len(contribDocs) > 0 {
		buf.WriteString("## Contributing\n\n")
		buf.WriteString("See original documentation:\n\n")
		for _, doc := range contribDocs {
			buf.WriteString(fmt.Sprintf("- [%s](file://%s)\n", doc.Path, doc.Path))
		}
		buf.WriteString("\n")
	}

	// License
	licenseDocs := g.filterByType(result.DiscoveredDocs, DocsTypeLicense)
	if len(licenseDocs) > 0 {
		buf.WriteString("## License\n\n")
		buf.WriteString("See original documentation:\n\n")
		for _, doc := range licenseDocs {
			buf.WriteString(fmt.Sprintf("- [%s](file://%s)\n", doc.Path, doc.Path))
		}
		buf.WriteString("\n")
	}

	// Changelog
	changelogDocs := g.filterByType(result.DiscoveredDocs, DocsTypeChangelog)
	if len(changelogDocs) > 0 {
		buf.WriteString("## Changelog\n\n")
		buf.WriteString("See original documentation:\n\n")
		for _, doc := range changelogDocs {
			buf.WriteString(fmt.Sprintf("- [%s](file://%s)\n", doc.Path, doc.Path))
		}
		buf.WriteString("\n")
	}

	buf.WriteString("---\n\n")
	buf.WriteString(g.formatTraceabilityBlock(result, "GOVERNANCE.md"))
	buf.WriteString("\n\n*This governance document was generated by KDSE Normalization from existing documentation.*\n")
	buf.WriteString("*Original documentation is preserved in its original location.*\n")
	buf.WriteString(fmt.Sprintf("*Generated: %s*\n", time.Now().Format(time.RFC3339)))

	content := buf.String()
	path := filepath.Join(g.kdseDir, "GOVERNANCE.md")
	if err := g.writeArtifact(path, content); err != nil {
		return nil, err
	}

	return &NormalizedArtifact{
		ID:       "NORM-GOV-" + g.sessionID,
		Path:     path,
		DocType:  "Governance",
		Title:    "Project Governance",
		Content:  content,
		Traceability: Traceability{
			DerivedFrom:       g.getDerivedFrom(result, DocsTypeContributing, DocsTypeLicense, DocsTypeChangelog),
			OriginalDocuments: g.getOriginalDocPaths(result),
			Authority:         g.getAuthority(result),
			Version:           kdseVersion,
			NormativeRefs:     []string{"docs/foundation/006-chain-of-authority.md"},
			TransformationType: "Normalization",
		},
		Metadata: ArtifactMetadata{
			Version:     kdseVersion,
			KDSEVersion: kdseVersion,
			Phase:       string(types.PhaseValidated),
			Tags:        []string{"normalized", "governance"},
		},
		CreatedAt: time.Now().Format(time.RFC3339),
	}, nil
}

func (g *Generator) generateAPI(result *NormalizationResult) (*NormalizedArtifact, error) {
	var buf strings.Builder
	buf.WriteString("# API Reference\n\n")
	buf.WriteString("**Document Version:** " + kdseVersion + "\n")
	buf.WriteString("**Type:** Engineering Artifact\n")
	buf.WriteString("**Phase:** Derived\n\n")
	buf.WriteString("---\n\n")
	buf.WriteString("## Overview\n\n")
	buf.WriteString("This API reference was compiled from existing API documentation.\n\n")

	// Link to original docs
	apiDocs := g.filterByType(result.DiscoveredDocs, DocsTypeAPI)
	if len(apiDocs) > 0 {
		buf.WriteString("## Source Documentation\n\n")
		for _, doc := range apiDocs {
			buf.WriteString(fmt.Sprintf("- [%s](file://%s)\n", doc.Path, doc.Path))
		}
		buf.WriteString("\n")
	}

	buf.WriteString("---\n\n")
	buf.WriteString(g.formatTraceabilityBlock(result, "API.md"))
	buf.WriteString("\n\n*This API reference was generated by KDSE Normalization from existing documentation.*\n")
	buf.WriteString("*Original documentation is preserved in its original location.*\n")
	buf.WriteString(fmt.Sprintf("*Generated: %s*\n", time.Now().Format(time.RFC3339)))

	content := buf.String()
	path := filepath.Join(g.kdseDir, "API.md")
	if err := g.writeArtifact(path, content); err != nil {
		return nil, err
	}

	return &NormalizedArtifact{
		ID:       "NORM-API-" + g.sessionID,
		Path:     path,
		DocType:  "API Reference",
		Title:    "API Reference",
		Content:  content,
		Traceability: Traceability{
			DerivedFrom:       g.getDerivedFrom(result, DocsTypeAPI),
			OriginalDocuments: g.getOriginalDocPaths(result),
			Authority:         g.getAuthority(result),
			Version:           kdseVersion,
			NormativeRefs:     []string{"docs/foundation/005-engineering-artifacts.md"},
			TransformationType: "Normalization",
		},
		Metadata: ArtifactMetadata{
			Version:     kdseVersion,
			KDSEVersion: kdseVersion,
			Phase:       string(types.PhaseUsable),
			Tags:        []string{"normalized", "api"},
		},
		CreatedAt: time.Now().Format(time.RFC3339),
	}, nil
}

func (g *Generator) generateArtifactsIndex(result *NormalizationResult, artifacts []NormalizedArtifact) (*NormalizedArtifact, error) {
	var buf strings.Builder
	buf.WriteString("# KDSE Artifacts Index\n\n")
	buf.WriteString("**Document Version:** " + kdseVersion + "\n")
	buf.WriteString("**Type:** Engineering Artifact\n")
	buf.WriteString("**Phase:** Derived\n\n")
	buf.WriteString("---\n\n")
	buf.WriteString("## Overview\n\n")
	buf.WriteString("This index lists all KDSE-standard artifacts generated from existing documentation.\n\n")
	buf.WriteString(fmt.Sprintf("**Session ID:** %s\n", result.SessionID))
	buf.WriteString(fmt.Sprintf("**Normalized:** %s\n\n", result.CompletedAt))

	buf.WriteString("## Artifacts\n\n")
	buf.WriteString("| Artifact | Path | Traceability |\n")
	buf.WriteString("|----------|------|-------------|\n")
	for _, artifact := range artifacts {
		buf.WriteString(fmt.Sprintf("| %s | %s | [Details](#%s) |\n",
			artifact.Title,
			filepath.Base(artifact.Path),
			strings.ToLower(strings.ReplaceAll(artifact.Title, " ", "-"))))
	}

	buf.WriteString("\n## Traceability Matrix\n\n")
	buf.WriteString("| KDSE Artifact | Derived From | Original Documents |\n")
	buf.WriteString("|---------------|--------------|-------------------|\n")
	for _, artifact := range artifacts {
		derivedFrom := ""
		for i, df := range artifact.Traceability.DerivedFrom {
			if i > 0 {
				derivedFrom += ", "
			}
			derivedFrom += filepath.Base(df.Path)
		}
		origDocs := ""
		for i, doc := range artifact.Traceability.OriginalDocuments {
			if i > 0 {
				origDocs += ", "
			}
			origDocs += filepath.Base(doc)
		}
		buf.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
			artifact.Title,
			derivedFrom,
			origDocs))
	}

	buf.WriteString("\n## Preserved Documentation\n\n")
	buf.WriteString("The following original documentation was preserved unchanged:\n\n")
	for _, doc := range result.PreservedDocs {
		buf.WriteString(fmt.Sprintf("- %s\n", doc))
	}

	buf.WriteString("\n---\n\n")
	buf.WriteString(g.formatTraceabilityBlock(result, "ARTIFACTS.md"))
	buf.WriteString("\n\n*This index was generated by KDSE Normalization.*\n")
	buf.WriteString("*Original documentation is preserved in its original location.*\n")
	buf.WriteString(fmt.Sprintf("*Generated: %s*\n", time.Now().Format(time.RFC3339)))

	content := buf.String()
	path := filepath.Join(g.kdseDir, "ARTIFACTS.md")
	if err := g.writeArtifact(path, content); err != nil {
		return nil, err
	}

	return &NormalizedArtifact{
		ID:       "NORM-IDX-" + g.sessionID,
		Path:     path,
		DocType:  "Artifacts Index",
		Title:    "KDSE Artifacts Index",
		Content:  content,
		Traceability: Traceability{
			DerivedFrom:       []DerivedFrom{},
			OriginalDocuments: g.getOriginalDocPaths(result),
			Authority:         g.getAuthority(result),
			Version:           kdseVersion,
			NormativeRefs:     []string{"docs/foundation/005-engineering-artifacts.md"},
			TransformationType: "Index",
		},
		Metadata: ArtifactMetadata{
			Version:     kdseVersion,
			KDSEVersion: kdseVersion,
			Phase:       string(types.PhaseValidated),
			Tags:        []string{"normalized", "index"},
		},
		CreatedAt: time.Now().Format(time.RFC3339),
	}, nil
}

// Helper methods

func (g *Generator) writeArtifact(path, content string) error {
	return os.WriteFile(path, []byte(content), 0644)
}

func (g *Generator) filterByType(docs []DiscoveredDocument, types ...DocType) []DiscoveredDocument {
	typeMap := make(map[DocType]bool)
	for _, t := range types {
		typeMap[t] = true
	}

	var filtered []DiscoveredDocument
	for _, doc := range docs {
		if typeMap[doc.Type] {
			filtered = append(filtered, doc)
		}
	}
	return filtered
}

func (g *Generator) getAuthority(result *NormalizationResult) string {
	if len(result.KnowledgeExtract.Stakeholders) > 0 {
		return result.KnowledgeExtract.Stakeholders[0]
	}
	return "Project Maintainers"
}

func (g *Generator) getOriginalDocPaths(result *NormalizationResult) []string {
	var paths []string
	for _, doc := range result.DiscoveredDocs {
		paths = append(paths, doc.Path)
	}
	return paths
}

func (g *Generator) getDerivedFrom(result *NormalizationResult, types ...DocType) []DerivedFrom {
	typeMap := make(map[DocType]bool)
	for _, t := range types {
		typeMap[t] = true
	}

	var derived []DerivedFrom
	for _, doc := range result.DiscoveredDocs {
		if typeMap[doc.Type] {
			derived = append(derived, DerivedFrom{
				Path:     doc.Path,
				DocType:  string(doc.Type),
				Confidence: fmt.Sprintf("%.0f%%", doc.Confidence*100),
			})
		}
	}
	return derived
}

func (g *Generator) getDerivedFromFromGlossary(glossary []GlossaryTerm) []DerivedFrom {
	sourceMap := make(map[string]bool)
	var derived []DerivedFrom
	for _, term := range glossary {
		if !sourceMap[term.Source] {
			sourceMap[term.Source] = true
			derived = append(derived, DerivedFrom{
				Path:     term.Source,
				DocType:  "Glossary",
				Confidence: "100%",
			})
		}
	}
	return derived
}

func (g *Generator) formatPurpose(k KnowledgeExtraction) string {
	if k.Purpose != "" {
		return k.Purpose
	}
	return "This project provides [see original documentation for details]"
}

func (g *Generator) formatDomain(k KnowledgeExtraction) string {
	if k.Domain != "" {
		return k.Domain
	}
	return "Software Engineering"
}

func (g *Generator) formatStakeholders(k KnowledgeExtraction) string {
	if len(k.Stakeholders) == 0 {
		return "See original documentation for stakeholder information"
	}
	var buf strings.Builder
	for _, s := range k.Stakeholders {
		buf.WriteString(fmt.Sprintf("- %s\n", s))
	}
	return buf.String()
}

func (g *Generator) formatRequirements(k KnowledgeExtraction) string {
	if len(k.Requirements) == 0 {
		return "See original documentation for requirements"
	}
	var buf strings.Builder
	for i, r := range k.Requirements {
		buf.WriteString(fmt.Sprintf("%d. %s\n", i+1, r.Description))
		buf.WriteString(fmt.Sprintf("   - Source: %s\n", r.Source))
	}
	return buf.String()
}

func (g *Generator) formatConstraints(k KnowledgeExtraction) string {
	if len(k.Constraints) == 0 {
		return "No explicit constraints defined"
	}
	var buf strings.Builder
	for _, c := range k.Constraints {
		buf.WriteString(fmt.Sprintf("- %s\n", c))
	}
	return buf.String()
}

func (g *Generator) formatOverview(result *NormalizationResult) string {
	return fmt.Sprintf("This architecture was derived from %d existing documentation files.",
		len(result.DiscoveredDocs))
}

func (g *Generator) formatDecisions(k KnowledgeExtraction) string {
	if len(k.Decisions) == 0 {
		return "See original documentation for architectural decisions"
	}
	var buf strings.Builder
	for _, d := range k.Decisions {
		buf.WriteString(fmt.Sprintf("- [%s] %s: %s\n", d.ID, d.Title, d.Decision))
	}
	return buf.String()
}

func (g *Generator) formatComponents(result *NormalizationResult) string {
	return "See original architecture documentation for component details"
}

func (g *Generator) formatTraceabilityBlock(result *NormalizationResult, artifactName string) string {
	var buf strings.Builder
	buf.WriteString("## Traceability\n\n")
	buf.WriteString(fmt.Sprintf("**Artifact ID:** NORM-%s\n", result.SessionID))
	buf.WriteString(fmt.Sprintf("**Derived From:** %d source documents\n", len(result.DiscoveredDocs)))
	buf.WriteString("**Original Documents:**\n")
	for _, doc := range result.DiscoveredDocs {
		buf.WriteString(fmt.Sprintf("  - %s (%s)\n", doc.Path, doc.Type))
	}
	return buf.String()
}
